services:
  user_db:
    container_name: user_db
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:27017
    volumes:
      - ./mongo-data:/data/db
    restart: unless-stopped
