export const UserErrors = {
  USER_NOT_FOUND: 'User not found',
  USER_ALREADY_EXISTS: 'User already exists',
  USER_NOT_FOUND_OR_DELETED: 'User not found or deleted',
  USER_UPDATE_FAILED: 'User update failed',
  USER_DELETION_FAILED: 'User deletion failed',
  USER_NOT_ACTIVE: 'User not active',
  USER_NOT_AUTHENTICATED: 'User not authenticated',
  USER_PERMISSION_DENIED: 'User permission denied',
  USER_VALIDATION_FAILED: 'Validation failed',
  USER_INVALID_CREDENTIALS: 'Invalid user credentials',
  USER_EMAIL_ALREADY_EXISTS: 'User email already exists',
  USER_PASSWORD_INCORRECT: 'User password incorrect',
  USER_NOT_AUTHORIZED: 'User not authorized',
  USER_PROFILE_UPDATE_FAILED: 'User profile update failed',
  USER_ADDRESS_NOT_FOUND: 'User address not found',
  USER_ADDRESS_ALREADY_EXISTS: 'User address already exists',
  USER_ROLE_NOT_VALID: 'User role not valid',
};
